name: Deploy static site to EC2 with Nginx2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Copy HTML to EC2 and restart Nginx
      run: |
        scp -o StrictHostKeyChecking=no index.html ubuntu@${{ secrets.EC2_HOST }}:/tmp/index.html
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} <<EOF
          sudo mv /tmp/index.html /var/www/html/index.html
          sudo systemctl restart nginx
        EOF
